import type { SiteContent } from './types.ts';

// TODO: thay bằng nội dung thật của công ty (tên, slogan, số liệu).
export const content: SiteContent = {
  locale: 'vi',
  seo: {
    title: 'Công ty Du lịch Việt — Tour trong nước trọn gói từ 2013',
    description:
      'Công ty lữ hành có giấy phép, tổ chức tour trong nước từ Sa Pa đến Phú Quốc. 12 năm kinh nghiệm, hơn 8.500 lượt khách, đánh giá trung bình 4,9/5.',
    ogLocale: 'vi_VN',
  },
  nav: [
    { anchor: 'about', label: 'Về chúng tôi' },
    { anchor: 'tours', label: 'Tour du lịch' },
    { anchor: 'destinations', label: 'Điểm đến' },
    { anchor: 'clients', label: 'Khách hàng' },
    { anchor: 'contact', label: 'Liên hệ' },
  ],
  langSwitch: {
    toOther: 'View the English version',
    labelEn: 'EN',
    labelVi: 'VI',
  },
  header: {
    navLabel: 'Điều hướng chính',
    callCta: 'Tư vấn miễn phí',
    openMenu: 'Mở menu',
    closeMenu: 'Đóng menu',
    skipToContent: 'Bỏ qua, tới nội dung chính',
  },
  hero: {
    overline: 'Lữ hành có giấy phép · Từ 2013',
    heading: 'Khám phá Việt Nam cùng người bản địa',
    tagline: 'từng thung lũng, từng khúc biển, từng bữa ăn đáng để dừng chân',
    description:
      'Chúng tôi thiết kế và tổ chức tour trọn gói khắp ba miền — từ ruộng bậc thang Sa Pa, hang động Quảng Bình đến những hòn đảo phương Nam.',
    ctaPrimary: 'Gọi tư vấn miễn phí',
    ctaSecondary: 'Xem tour trong nước',
    trustLine: '12 năm · hơn 8.500 lượt khách · đánh giá 4,9/5',
    imageAlt: 'Ruộng bậc thang lúa chín vàng trên sườn đồi Sa Pa',
  },
  statsHeading: 'Năng lực của chúng tôi qua con số',
  stats: [
    { value: 12, label: 'năm tổ chức tour trong nước' },
    { value: 8500, suffix: '+', label: 'lượt khách đã phục vụ' },
    { value: 640, suffix: '+', label: 'chuyến đã khởi hành' },
    { value: 4.9, decimals: 1, label: 'điểm đánh giá trung bình trên 5' },
  ],
  about: {
    overline: 'Về chúng tôi',
    heading: 'Công ty lữ hành, không phải trang đặt chỗ',
    body: [
      'Chúng tôi là công ty lữ hành Việt Nam, trụ sở tại TP. Hồ Chí Minh. Mọi hành trình chúng tôi bán đều là hành trình chúng tôi đã tự đi, với hướng dẫn viên lớn lên ở chính vùng đất đó.',
      'Chúng tôi tự tổ chức đoàn chứ không bán lại chỗ của đơn vị khác. Nghĩa là khi kế hoạch thay đổi — bão ở Quảng Bình, đường lên Sa Pa tắc — người bạn gọi chính là người quyết được.',
    ],
    licenseLabel: 'Giấy phép lữ hành quốc tế',
    imageAlt: 'Phố cổ Hội An lên đèn buổi tối',
  },
  whyUs: {
    overline: 'Vì sao chọn chúng tôi',
    heading: 'Điều một trang đặt chỗ không làm được cho bạn',
    description:
      'Chúng tôi chỉ làm tour trong nước. Hẹp lại là có chủ đích — nhờ vậy mới biết đoạn đường nào ngập tháng Mười, homestay nào thực sự có nước nóng.',
    items: [
      { icon: 'map', title: 'Am hiểu từng vùng miền', description: 'Bắc — Trung — Nam, hướng dẫn viên sống ở chính nơi họ đưa bạn đến.' },
      { icon: 'wallet', title: 'Báo giá theo đoàn', description: 'Cho biết số khách và nhu cầu, chúng tôi báo trọn gói, không phát sinh ẩn.' },
      { icon: 'clock', title: 'Phản hồi trong một giờ', description: 'Làm việc 8:00–20:00 cả tuần, qua điện thoại hoặc Zalo.' },
      { icon: 'users', title: 'Hướng dẫn viên thật', description: 'Có thẻ hành nghề, kể được câu chuyện sau mỗi điểm đến, tiếng Việt hoặc tiếng Anh.' },
      { icon: 'headset', title: 'Luôn liên lạc được', description: 'Một số điện thoại duy nhất trước, trong và sau chuyến đi.' },
      { icon: 'shield', title: 'Có giấy phép, có bảo hiểm', description: 'Giấy phép lữ hành quốc tế, mọi chuyến đều có bảo hiểm du lịch.' },
    ],
  },
  tours: {
    overline: 'Tour du lịch',
    heading: 'Sáu hành trình chúng tôi tự tổ chức',
    description:
      'Mọi chuyến dưới đây đều do đội ngũ của chúng tôi tổ chức, không bán lại của đơn vị khác. Đoàn giữ nhỏ để còn đổi được lịch khi thời tiết đổi.',
    filters: { all: 'Tất cả', bac: 'Miền Bắc', trung: 'Miền Trung', nam: 'Miền Nam' },
    durationLabel: 'Thời lượng',
    detailCta: 'Xem lịch trình',
    itineraryLabel: 'Lịch trình từng ngày',
    quoteNote: 'Giá tuỳ số lượng khách và mùa — gọi hoặc nhắn tin để nhận báo giá.',
    items: [
      {
        slug: 'sapa-trek',
        region: 'bac',
        name: 'Sa Pa và thung lũng Mường Hoa đi bộ',
        province: 'Lào Cai',
        duration: '3 ngày 2 đêm',
        highlights: [
          'Hai ngày đi bộ qua các bản người Mông và người Dao',
          'Một đêm homestay nhà dân, một đêm trong thị trấn',
          'Hướng dẫn viên người bản địa, nói được tiếng dân tộc',
        ],
        itinerary: [
          { label: 'Ngày 1', detail: 'Từ Hà Nội lên Sa Pa, chiều đi bộ xuống bản Lao Chải.' },
          { label: 'Ngày 2', detail: 'Trọn ngày trek qua Tả Van và Giàng Tà Chải, tối ăn cùng gia đình chủ nhà.' },
          { label: 'Ngày 3', detail: 'Sáng đi chợ phiên, tối về tới Hà Nội.' },
        ],
        imageAlt: 'Khách đi bộ cùng phụ nữ người Mông trên đường mòn gần Sa Pa',
      },
      {
        slug: 'halong-cruise',
        region: 'bac',
        name: 'Ngủ đêm trên thuyền gỗ vịnh Hạ Long',
        province: 'Quảng Ninh',
        duration: '2 ngày 1 đêm',
        highlights: [
          'Ngủ lại trên thuyền, tránh giờ cao điểm khách đi trong ngày',
          'Chèo kayak vào hang Luồn lúc sớm mai',
          'Tối đa 16 khách mỗi thuyền',
        ],
        itinerary: [
          { label: 'Ngày 1', detail: 'Trưa lên thuyền, ăn trưa khi thuyền chạy, chiều kayak và tắm biển, tối ăn trên boong.' },
          { label: 'Ngày 2', detail: 'Ngắm bình minh giữa núi đá, thăm hang, đầu giờ chiều về bờ.' },
        ],
        imageAlt: 'Thuyền buồm gỗ giữa các đảo đá vôi vịnh Hạ Long',
      },
      {
        slug: 'phongnha-cave',
        region: 'trung',
        name: 'Phong Nha và động Thiên Đường',
        province: 'Quảng Bình',
        duration: '2 ngày 1 đêm',
        highlights: [
          'Đi thuyền trên sông Son vào động Phong Nha',
          'Đi bộ một cây số đầu tiên trong động Thiên Đường',
          'Chiều tắm suối Nước Moọc',
        ],
        itinerary: [
          { label: 'Ngày 1', detail: 'Thuyền sông Son vào động Phong Nha, chiều nghỉ ở suối Nước Moọc.' },
          { label: 'Ngày 2', detail: 'Sáng vào động Thiên Đường, chiều về Đồng Hới kịp chuyến tàu tối.' },
        ],
        imageAlt: 'Nhũ đá và lối đi trong động Thiên Đường, Quảng Bình',
      },
      {
        slug: 'hue-hoian',
        region: 'trung',
        name: 'Huế – Hội An qua đèo Hải Vân',
        province: 'Thừa Thiên Huế · Quảng Nam',
        duration: '4 ngày 3 đêm',
        highlights: [
          'Đại Nội và hai lăng vua ở Huế',
          'Vượt đèo Hải Vân, dừng ở những chỗ đáng dừng',
          'Hai đêm trong phố cổ Hội An',
        ],
        itinerary: [
          { label: 'Ngày 1', detail: 'Tới Huế, chiều thăm Đại Nội, tối ăn bên sông Hương.' },
          { label: 'Ngày 2', detail: 'Lăng Tự Đức và lăng Khải Định, chiều tự do.' },
          { label: 'Ngày 3', detail: 'Vượt đèo Hải Vân về Hội An, tối phố cổ lên đèn.' },
          { label: 'Ngày 4', detail: 'Đi bộ phố cổ, Chùa Cầu, rời đi từ Đà Nẵng.' },
        ],
        imageAlt: 'Chùa Cầu Hội An soi bóng xuống kênh',
      },
      {
        slug: 'mekong-tour',
        region: 'nam',
        name: 'Chợ nổi Cái Răng và miệt vườn',
        province: 'Cần Thơ',
        duration: '2 ngày 1 đêm',
        highlights: [
          'Xuống ghe lúc 5g30, trước khi chợ vãn',
          'Một đêm ở nhà dân ven kênh',
          'Xem làm hủ tiếu và đi vườn trái cây',
        ],
        itinerary: [
          { label: 'Ngày 1', detail: 'TP. Hồ Chí Minh đi Cần Thơ, chiều đi ghe trong kênh, tối ăn cùng chủ nhà.' },
          { label: 'Ngày 2', detail: 'Dậy sớm đi chợ nổi Cái Răng, ghé lò hủ tiếu, chiều về.' },
        ],
        imageAlt: 'Ghe chở đầy nông sản ở chợ nổi Cái Răng',
      },
      {
        slug: 'dalat-tour',
        region: 'nam',
        name: 'Đà Lạt: hoa, cà phê và rừng thông',
        province: 'Lâm Đồng',
        duration: '3 ngày 2 đêm',
        highlights: [
          'Thăm một nông trại cà phê thật, từ quả tới ly',
          'Vườn hoa và ga xe lửa cũ',
          'Đêm lạnh — nhớ mang áo khoác, kể cả tháng Bảy',
        ],
        itinerary: [
          { label: 'Ngày 1', detail: 'Tới Đà Lạt, chiều đi vườn hoa, tối ra chợ đêm.' },
          { label: 'Ngày 2', detail: 'Nông trại cà phê và xưởng rang, chiều ra hồ Tuyền Lâm.' },
          { label: 'Ngày 3', detail: 'Ga xe lửa cũ, dinh Bảo Đại, rồi khởi hành về.' },
        ],
        imageAlt: 'Xe ngựa bên luống hoa trong một vườn hoa Đà Lạt',
      },
    ],
  },
  destinations: {
    overline: 'Điểm đến',
    heading: 'Chín nơi chúng tôi thuộc đường',
    description: 'Tất cả đều trong nước. Bắc, Trung, Nam — vuốt để xem.',
    prevLabel: 'Xem các điểm đến trước',
    nextLabel: 'Xem các điểm đến tiếp theo',
    items: [
      { slug: 'ha-long', name: 'Vịnh Hạ Long', region: 'bac', tourCount: '4 tour', imageAlt: 'Núi đá vôi nhô lên khỏi mặt nước vịnh Hạ Long' },
      { slug: 'sapa', name: 'Sa Pa', region: 'bac', tourCount: '3 tour', imageAlt: 'Ruộng bậc thang xanh ở thung lũng Mường Hoa' },
      { slug: 'ninh-binh', name: 'Ninh Bình', region: 'bac', tourCount: '2 tour', imageAlt: 'Thuyền chèo vào hang trên sông Tràng An' },
      { slug: 'hue', name: 'Huế', region: 'trung', tourCount: '3 tour', imageAlt: 'Cổng trang trí của Đại Nội Huế' },
      { slug: 'hoi-an', name: 'Hội An', region: 'trung', tourCount: '5 tour', imageAlt: 'Dãy nhà vàng trong phố cổ Hội An' },
      { slug: 'da-nang', name: 'Đà Nẵng', region: 'trung', tourCount: '3 tour', imageAlt: 'Cầu Rồng Đà Nẵng lên đèn ban đêm' },
      { slug: 'phong-nha', name: 'Phong Nha', region: 'trung', tourCount: '2 tour', imageAlt: 'Cửa hang và dòng sông xanh ở Phong Nha' },
      { slug: 'da-lat', name: 'Đà Lạt', region: 'nam', tourCount: '2 tour', imageAlt: 'Luống hoa trong một vườn hoa Đà Lạt' },
      { slug: 'mekong', name: 'Miền Tây', region: 'nam', tourCount: '3 tour', imageAlt: 'Ghe chở nông sản trên sông miền Tây' },
    ],
  },
  mobileBar: {
    call: 'Gọi ngay',
    zalo: 'Zalo',
    messenger: 'Nhắn tin',
  },
};
